apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "opstestcluster-2f5a"
    labels:
        app: "opstestcluster-2f5a"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: ops-test-nhgis-assets-opstestcluster-2f5a.7a691896395b4063902a.centralus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "opstestcluster-2f5a"
                servicePort: 80