on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: opsarc.azurecr.io
        username: ${{ secrets.acr_opsarc_username }}
        password: ${{ secrets.acr_opsarc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t opsarc.azurecr.io/opstestcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push opsarc.azurecr.io/opstestcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_opstestcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ops-nhgis-assets | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ops-nhgis-assets`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ops-nhgis-assets
        container-registry-url: opsarc.azurecr.io
        container-registry-username: ${{ secrets.acr_opsarc_username }}
        container-registry-password: ${{ secrets.acr_opsarc_password }}
        secret-name: opstestclustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ops-nhgis-assets
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          opsarc.azurecr.io/opstestcluster:${{ github.sha }}
        imagepullsecrets: |
          opstestclustdockerauth
